/**
 * The sales report as a PDF — the export the portal never had.
 *
 * The phone has offered CSV and PDF side by side for months; the portal offered
 * CSV alone, so an owner sitting at the counter machine could not produce the
 * one document you can actually hand to an accountant or attach to an email.
 *
 * PRINTED, NOT GENERATED. No pdf library: the browser already has an excellent
 * PDF writer behind the print dialog, and a library to avoid one dialog would
 * be the single largest thing in this bundle. Same reasoning that keeps the
 * growth chart as inline SVG, and the same technique the bills already use.
 *
 * TAKES ReportCsvInput, deliberately -- the exact type the CSV builder takes.
 * Two exports of the same report that read their inputs differently is how the
 * PDF and the spreadsheet come to disagree about a total, and nobody would know
 * which to believe.
 *
 * A NEW WINDOW, NOT AN IFRAME. Printing an iframe prints the host page in
 * several browsers, and the host page here is the portal with its navigation.
 * A document of its own has nothing else on it to get into the paper.
 */
import type { ReportCsvInput } from './reportCsv';

const esc = (s: unknown) =>
  String(s ?? '').replace(/[&<>"]/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string
  ));

const inr = (n: number) => '₹' + Math.round(Number(n ?? 0)).toLocaleString('en-IN');

const when = (d: Date) => {
  try {
    return d.toLocaleString('en-IN', {
      day: 'numeric', month: 'short', year: 'numeric',
      hour: 'numeric', minute: '2-digit', hour12: true,
    });
  } catch { return d.toISOString(); }
};

export function buildReportHtml(r: ReportCsvInput): string {
  const rows = r.points
    .map((p) => `<tr><td>${esc(p.label)}</td><td class="n">${inr(p.revenue)}</td><td class="n">${p.orders}</td></tr>`)
    .join('');

  const items = r.topItems.length
    ? r.topItems
        .map((i, n) => `<tr><td>${n + 1}. ${esc(i.name)}</td><td class="n">${i.qty}</td><td class="n">${inr(i.revenue)}</td></tr>`)
        .join('')
    : '<tr><td colspan="3" class="dim">No items sold in this period.</td></tr>';

  const hours = r.peakHours.length
    ? r.peakHours.map((h) => `<li>${esc(h.label)}</li>`).join('')
    : '<li class="dim">Not enough orders to tell yet.</li>';

  return `<!doctype html><html><head><meta charset="utf-8">
<title>Menutha report — ${esc(r.restaurantName)}</title>
<style>
  @page { size: A4; margin: 14mm; }
  * { box-sizing: border-box; }
  body { margin: 0; font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
         color: #1C1A15; font-size: 11pt; }
  h1 { font-size: 17pt; margin: 0 0 2mm; }
  h2 { font-size: 12pt; margin: 8mm 0 2mm; }
  .sub { color: #6B6557; font-size: 9.5pt; margin: 0; }
  .kpis { display: flex; gap: 6mm; margin: 6mm 0 0; }
  .kpi { flex: 1; border: 1px solid #E7DECC; border-radius: 3mm; padding: 4mm; }
  .kpi b { display: block; font-size: 15pt; }
  .kpi span { color: #6B6557; font-size: 9pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 2mm; }
  th, td { text-align: left; padding: 1.6mm 2mm; border-bottom: 1px solid #EFE8DA; font-size: 10pt; }
  th { color: #6B6557; font-weight: 600; font-size: 9pt; text-transform: uppercase; letter-spacing: 0.04em; }
  /* Money and counts right-aligned with tabular figures, so a column of
     numbers reads as a column rather than as ragged text. */
  .n { text-align: right; font-variant-numeric: tabular-nums; }
  .dim { color: #8A8475; }
  ul { margin: 2mm 0 0 5mm; padding: 0; font-size: 10pt; }
  .foot { margin-top: 9mm; color: #8A8475; font-size: 8.5pt; }
  /* A table that runs onto a second page repeats its header rather than
     leaving the reader guessing which column is which. */
  thead { display: table-header-group; }
  tr { break-inside: avoid; }
</style></head><body>
  <h1>${esc(r.restaurantName)}</h1>
  <p class="sub">Sales report · ${esc(r.periodLabel)} · covers ${esc(r.from)} to ${esc(r.to)}</p>

  <div class="kpis">
    <div class="kpi"><b>${inr(r.totalRevenue)}</b><span>Revenue</span></div>
    <div class="kpi"><b>${r.totalOrders}</b><span>Orders</span></div>
    <div class="kpi"><b>${r.totalOrders ? inr(r.totalRevenue / r.totalOrders) : '—'}</b><span>Average order</span></div>
  </div>

  <h2>Day by day</h2>
  <table>
    <thead><tr><th>Period</th><th class="n">Revenue</th><th class="n">Orders</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>

  <h2>Top items</h2>
  <table>
    <thead><tr><th>Item</th><th class="n">Qty</th><th class="n">Revenue</th></tr></thead>
    <tbody>${items}</tbody>
  </table>

  <h2>Busiest hours</h2>
  <ul>${hours}</ul>

  <p class="foot">
    Generated by Menutha on ${esc(when(r.generatedAt))}. Cancelled orders are not counted.
  </p>
</body></html>`;
}

/**
 * Open the report in its own window and raise the print dialog.
 *
 * Returns false when the window could not be opened, which on the web means
 * exactly one thing: a pop-up blocker. The caller says so rather than leaving
 * a button that visibly does nothing -- the failure people report as "the PDF
 * button is broken".
 */
export function printReportPdf(r: ReportCsvInput): boolean {
  const w = window.open('', '_blank');
  if (!w) return false;
  w.document.write(buildReportHtml(r));
  w.document.close();
  // The dialog has to wait for layout, or it measures an empty document and
  // prints a blank first page.
  w.onload = () => { w.focus(); w.print(); };
  // Some browsers fire load before the write completes; this is the fallback
  // for those, and printing twice is harmless because the dialog is modal.
  setTimeout(() => { try { w.focus(); w.print(); } catch { /* window closed */ } }, 400);
  return true;
}
